import React, { useState } from 'react';
import {
  Button,
  ButtonGroup,
  Card,
  Container,
  Col,
  Form,
  Row,
  Table,
  Spinner
} from 'react-bootstrap';
import "./Quotation.css"

const Quotation = () => {
  const [tableData, setTableData] = useState([])
  const [firstRow, setFirstRow] = useState({
    firstItem: "",
    firstQuantity: 0,
    fitstUnitPrice: 0
  })
  const handleChange = (event) => {
    const { name, value } = event.target;
    console.log(value)
    setFirstRow({
      ...firstRow,
      [name]: value
    })
  }
  console.log(firstRow)

return (
  <Container>
    <Card className="a4-card">
      <Card.Body>
        <Card.Title className="text-center">
          <h2>ใบเสนอราคา</h2>
        </Card.Title>
        <Card.Body>
          <Form>
            <Row>
              เรื่อง&nbsp;&nbsp;&nbsp;ขอเสนอราคา
            </Row>
            <br />
            <Row>
              เรียน
              <Col>
                <Form.Control
                  type="text"
                  name="dear"
                />
              </Col>
            </Row>
            <br />
            <Row>
              ข้าพเจ้า นางนุทยา ใจรักษ์ ร้านเปี๊ยกการช่าง ตั้งอยู่ที่ 119/435 ถนน ลำปาง-แม่ทะ ตำบล พระบาท
              <br />
              อำเภอ เมือง จังหวัด ลำปาง รหัสไปรษณีย์ 52000 ทะเบียนการค้า 90015335
              <br />
              เลขประจำตัวผู้เสียภาษีอากร 3520400137241 โทรศัพท์ 086-1168000
            </Row>
            <br />
            <Row>
              ขอเสนอราคาตามรายการด้านล่างเพื่อประกอบการพิจารณาการซ่อมรถหมายเลขทะเบียน
              <Col>
                <Form.Control
                  type="text"
                  name="dear"
                />
              </Col>
            </Row>
            <br />
            <Table bordered responsive hover size="sm">
              <thead>
                <tr>
                  <th>ลำดับที่</th>
                  <th>รายการ</th>
                  <th>จำนวน</th>
                  <th>ราคาต่อหน่วย</th>
                  <th>จำนวนเงิน (บาท)</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="firstItem"
                      onChange={handleChange}
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="firstQuantity"
                      onChange={handleChange}
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="fitstUnitPrice"
                      onChange={handleChange}
                    />
                  </td>
                  <td>{firstRow.firstQuantity * firstRow.fitstUnitPrice}
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
                <tr>
                  <td>1</td>
                  <td>
                    <Form.Control
                      type="text"
                      name="one"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                  <td>
                    <Form.Control
                      type="number"
                      name="two"
                    />
                  </td>
                </tr>
              </tbody>
            </Table>
            <ButtonGroup className="d-flex">
              <Button variant="primary" type="submit">
                บันทึก
              </Button>
            </ButtonGroup>

          </Form>
        </Card.Body>
      </Card.Body>
    </Card>
  </Container>
);

}

export default Quotation;
